#!/usr/bin/env php
<?php
////////////////////////////////////////////////////////////////////
//                          _ooOoo_                               //
//                         o8888888o                              //
//                         88" . "88                              //
//                         (| ^_^ |)                              //
//                         O\  =  /O                              //
//                      ____/`---'\____                           //
//                    .'  \\|     |//  `.                         //
//                   /  \\|||  :  |||//  \                        //
//                  /  _||||| -:- |||||-  \                       //
//                  |   | \\\  -  /// |   |                       //
//                  | \_|  ''\---/''  |   |                       //
//                  \  .-\__  `-`  ___/-. /                       //
//                ___`. .'  /--.--\  `. . ___                     //
//            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
//      ========`-.____`-.___\_____/___.-`____.-'========         //
//                           `=---='                              //
//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
//                           永无BUG                               //
////////////////////////////////////////////////////////////////////

$server = include_once 'Core/Core.php';
$server = \Core\Core::getInstance()->initialize();
/**
 *[commandParser 解释命令]
 * @author  Wongzx <[842687571@qq.com]>
 * @copyright Copyright (c)
 * @return    [type]        [description]
 */
function commandParser()
{
    global $argv; //$argv — 传递给脚本的参数数组
    $command = '';
    if (isset($argv[1])) {
        $command = $argv[1];
    }
    unset($argv[0]);
    $options = $argv;
    return [
        "command" => $command,
        "options" => $options
    ];
}

/**
 *[commandHandler 命令处理程序]
 * @author  Wongzx <[842687571@qq.com]>
 * @copyright Copyright (c)
 * @return    [type]        [description]
 */
function commandHandler()
{
    $comm = commandParser();
    switch ($comm['command']) {
        case 'start':
            startServer();
            break;
    }
}

function startServer()
{
    $string = <<<STRING
   ___    _ __    _     ___                          _           
  /   \  | '_ \  (_)   / __| __ __ __ ___    ___    | |    ___   
  | - |  | .__/  | |   \__ \ \ V  V // _ \  / _ \   | |   / -_)  
  |_|_|  |_|__  _|_|_  |___/  \_/\_/ \___/  \___/  _|_|_  \___|  
_|"""""||"""""||"""""||"""""||"""""||"""""||"""""||"""""||"""""| 
"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-' 
STRING;
    echo $string . "\n";

}

commandHandler();

