#!/usr/bin/env php
<?php
////////////////////////////////////////////////////////////////////
//                          _ooOoo_                               //
//                         o8888888o                              //
//                         88" . "88                              //
//                         (| ^_^ |)                              //
//                         O\  =  /O                              //
//                      ____/`---'\____                           //
//                    .'  \\|     |//  `.                         //
//                   /  \\|||  :  |||//  \                        //
//                  /  _||||| -:- |||||-  \                       //
//                  |   | \\\  -  /// |   |                       //
//                  | \_|  ''\---/''  |   |                       //
//                  \  .-\__  `-`  ___/-. /                       //
//                ___`. .'  /--.--\  `. . ___                     //
//            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
//      ========`-.____`-.___\_____/___.-`____.-'========         //
//                           `=---='                              //
//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
//                           永无BUG                               //
////////////////////////////////////////////////////////////////////

include_once 'Core/Core.php';
$server = \Core\Core::getInstance()->initialize();  //初始化
/**
 *[commandParser 解释命令]
 * @author  Wongzx <[842687571@qq.com]>
 * @copyright Copyright (c)
 * @return    [type]        [description]
 */
function commandParser()
{
    global $argv; //$argv — 传递给脚本的参数数组
    $command = '';
    if (isset($argv[1])) {
        $command = $argv[1];
    }
    unset($argv[0]);
    $options = $argv;
    return [
        "command" => $command,
        "options" => $options
    ];
}

/**
 *[commandHandler 命令处理程序]
 * @author  Wongzx <[842687571@qq.com]>
 * @copyright Copyright (c)
 * @return    [type]        [description]
 */
function commandHandler()
{
    $comm = commandParser();
    switch ($comm['command']) {
        case 'start': //启动
            startServer();
            break;
        case 'stop': //停止
            stopServer($comm['options']);
            break;
        case 'reload': //重载服务
            reloadServer($comm['options']);
            break;
        case 'update': //升级系统
            break;
        case 'version': //版本号
            echo "";
            break;
        case 'help': //帮助
        default: {
            help();
        }
    }
}


/**
 * startServer  [开启框架]
 * @copyright Copyright (c)
 * @author Wongzx <842687571@qq.com>
 */
function startServer()
{
    echo lconLogo() . "\n";
    global $server;
    $conf = \Conf\Config::getInstance();

    //IP
    echo 'listen address       ' . "\033[32m ".$conf->getConf('SERVER.LISTEN')." \033[0m" . "\n";

    //端口
    echo 'listen port          ' . "\033[32m ".$conf->getConf('SERVER.PORT')." \033[0m" . "\n";

    //进程数
    echo 'worker num           ' . "\033[32m ".$conf->getConf('SERVER.CONFIG.worker_num')." \033[0m" . "\n";

    //异步任务进程数
    echo 'task worker num      ' . "\033[32m ".$conf->getConf('SERVER.CONFIG.task_worker_num')." \033[0m" . "\n";


    $server->run();
}


function reloadServer($options)
{
    $pidFile = \Conf\Config::getInstance()->getConf("SERVER.CONFIG.pid_file");
    if (!empty($options['pid'])) {
        $pidFile = $options['pid'];
    }
    if (!file_exists($pidFile)) {
        echo "pid file :{$pidFile} not exist \n";
        return;
    }
    $pid = file_get_contents($pidFile);
    if (!swoole_process::kill($pid, 0)) {
        echo "pid :{$pid} not exist \n";
        return;
    }

    swoole_process::kill($pid, SIGUSR1);
    echo "send server reload command at " . date("y-m-d h:i:s") . "\n";
}

function stopServer($options)
{
    $pidFile = \Conf\Config::getInstance()->getConf("SERVER.CONFIG.pid_file");
    if (!empty($options['pid'])) {
        $pidFile = $options['pid'];
    }
    if (!file_exists($pidFile)) {
        echo "pid file :{$pidFile} not exist \n";
        return;
    }
    $pid = file_get_contents($pidFile);
    if (!swoole_process::kill($pid, 0)) {
        echo "pid :{$pid} not exist \n";
        return;
    }
    sleep(2);
    if (swoole_process::kill($pid, SIGTERM)) {
        echo "server stop at " . date("y-m-d h:i:s") . "\n";
        if (is_file($pidFile)) {
            unlink($pidFile);
        }
    } else {
        echo "stop server fail try again \n";
    }
}


function help()
{
    echo lconLogo() . "\n\n";
    echo "\033[36m ApiSwoole \033[0mversion \033[33m" . VERSION . " \033[0m" . date('Y-m-d H:i:s') . "\n\n";

    $helpString = <<<HELPSTRING
\033[32m start \033[0m           启动服务
\033[32m stop \033[0m            停止服务
\033[32m update \033[0m          升级系统
\033[32m reload \033[0m          重装服务
HELPSTRING;
    echo $helpString . "\n";


}

function lconLogo()
{
    $string = <<<STRING
   ___    _ __    _     ___                          _           
  /   \  | '_ \  (_)   / __| __ __ __ ___    ___    | |    ___   
  | - |  | .__/  | |   \__ \ \ V  V // _ \  / _ \   | |   / -_)  
  |_|_|  |_|__  _|_|_  |___/  \_/\_/ \___/  \___/  _|_|_  \___|  
_|"""""||"""""||"""""||"""""||"""""||"""""||"""""||"""""||"""""| 
"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-' 
STRING;

    return $string;
}

commandHandler();

